default:
    image: node:14-buster

before_script:
  - npm install

cache:
  paths:
    - node_modules/

stages:
    - lint
    - test

lint-job:
  stage: lint
  script:
    - npm run lint

test-job:
  stage: test
  script:
    - npm run ci-cd:test
