default:
    image: node:14-buster

stages:
    - npm-install
    - lint
    - test

build-job:
  stage: npm-install
  script:
    - npm install

lint-job:
  stage: lint
  script:
    - npm run lint

test-job:
  stage: test
  script:
    - npm run test
